#!/bin/sh
COMMBAD="/etc/nut/commbad"

case $1 in
  online)
    # if previously rebooted, then delete file
    logger -t upssched-cmd "NUT - Online"
  ;;
  onbatt)
    logger -t upssched-cmd "UPS running on battery"
  ;;
  earlyshutdown)
    logger -t upssched-cmd "NUT - Early shutdown time-out reached"
  ;;
  lowbatt)
    # shutdown all systems now
    logger -t upssched-cmd "NUT - UPS on battery critical, forced shutdown"
    /sbin/upsmon -c fsd
  ;;
  fsd)
    logger -t upssched-cmd "NUT - UPS forced shutdown started"
  ;;
  commok)
    logger -t upssched-cmd "NUT - UPS communications OK"
    # if file was created then delete file
    if [ -f $COMMBAD ]; then
       rm $COMMBAD
    fi
  ;;
  commbad)
    logger -t upssched-cmd "NUT - UPS communications has been offline too long"
   # check if file has already been created
   if [ -f $COMMBAD ]; then
      logger -t upssched-cmd "NUT - System has already created COMMBAD file"
   # if not create file for openhab
   else
      logger -t upssched-cmd "NUT - Creating COMMBAD file"
      touch $COMMBAD
   fi
  ;;
  shutdown)
    logger -t upssched-cmd "NUT - System shutdown started"
  ;;
  *)
    logger -t upssched-cmd "No code defined for command: $1"
  ;;
esac
